<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net9.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageProjectUrl>https://github.com/Sunlighter/GraphicsTerminal</PackageProjectUrl>
    <Description>Graphics Terminal Library</Description>
    <PackageId>Sunlighter.GraphicsTerminalLib</PackageId>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <AssemblyName>Sunlighter.GraphicsTerminalLib</AssemblyName>
    <Product>Sunlighter.GraphicsTerminalLib</Product>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>1.0.3</AssemblyVersion>
    <FileVersion>1.0.3</FileVersion>
    <Version>1.0.3</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sunlighter.OptionLib" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
